id: P20C2A85C
initial_creation_type: ocr
source_metadata:
  volumes:
    fd09a7d94339449a9563db9b90c1553f:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: སངས་རྒྱས་རྗེས་སུ་དྲན་པའི་འགྲེལ་པ།
      total_pages: 1498
      volume_number: 65
